table colony
	lineageTag: c135e0be-bc71-413f-9847-2b92140b2dcf

	column year
		dataType: double
		lineageTag: 8dbfefcf-e592-436e-9eec-0450eb2fcbc1
		summarizeBy: sum
		sourceColumn: year

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column months
		dataType: string
		lineageTag: 741855f6-4055-424e-895f-e7d5120335bb
		summarizeBy: none
		sourceColumn: months

		annotation SummarizationSetBy = Automatic

	column state
		dataType: string
		lineageTag: 6add6265-68c7-4507-b22f-fdd0a57f3450
		summarizeBy: none
		sourceColumn: state

		annotation SummarizationSetBy = Automatic

	column colony_n
		dataType: double
		lineageTag: 88da86c5-8c48-4c21-b9f1-e9cd7ecd6b19
		summarizeBy: sum
		sourceColumn: colony_n

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column colony_max
		dataType: double
		lineageTag: eb468a08-7919-46b8-a055-66f2d4f63420
		summarizeBy: sum
		sourceColumn: colony_max

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column colony_lost
		dataType: double
		lineageTag: 5b3e042d-70a6-496b-9655-2d48b4e6913e
		summarizeBy: sum
		sourceColumn: colony_lost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column colony_lost_pct
		dataType: double
		lineageTag: ef49da8a-7e24-4633-8dd3-5c08626b92b7
		summarizeBy: sum
		sourceColumn: colony_lost_pct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column colony_added
		dataType: double
		lineageTag: 306753de-73fa-460b-a0a9-169d6a7b84c7
		summarizeBy: sum
		sourceColumn: colony_added

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column colony_reno
		dataType: double
		lineageTag: 7add76c7-d266-4639-8080-d0760ce09414
		summarizeBy: sum
		sourceColumn: colony_reno

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column colony_reno_pct
		dataType: double
		lineageTag: aacb971c-bf1c-4419-af97-3deba9efd016
		summarizeBy: sum
		sourceColumn: colony_reno_pct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition colony = m
		mode: import
		source =
				let
					Source = Csv.Document(File.Contents("C:\Users\rshea\Downloads\colony.csv"),[Delimiter=",", Columns=10, Encoding=1252, QuoteStyle=QuoteStyle.None]),
					#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					#"Replaced Value" = Table.ReplaceValue(#"Promoted Headers","NA",null,Replacer.ReplaceValue,{"year", "months", "state", "colony_n", "colony_max", "colony_lost", "colony_lost_pct", "colony_added", "colony_reno", "colony_reno_pct"}),
					#"Changed Type" = Table.TransformColumnTypes(#"Replaced Value",{  {"year", type number}, {"months", type text}, {"state", type text}, {"colony_n", type number}, {"colony_max", type number}, {"colony_lost", type number}, {"colony_lost_pct", type number}, {"colony_added", type number}, {"colony_reno", type number}, {"colony_reno_pct", type number}   })
				in
					#"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

