table wa_bigfoot_by_county
	lineageTag: 28354c97-56db-47c1-b1d3-bd5c3019d338

	column 'county'
		dataType: string
		lineageTag: abbf3c49-6a6d-47cc-9bbd-19fb8e1d51f9
		summarizeBy: none
		sourceColumn: county

		annotation SummarizationSetBy = Automatic

	column 'season'
		dataType: string
		lineageTag: 40031788-6936-4141-9484-63864b306f4f
		summarizeBy: none
		sourceColumn: season

		annotation SummarizationSetBy = Automatic

	column 'count'
		dataType: double
		lineageTag: 077471e9-aef3-466f-9881-454c1df74557
		summarizeBy: sum
		sourceColumn: count

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition wa_bigfoot_by_county = m
		mode: import
		source =
				let
					Source = Csv.Document(File.Contents("C:\Users\rshea\Downloads\wa_bigfoot_by_county.csv"),[Delimiter=",", Columns=3, Encoding=1252, QuoteStyle=QuoteStyle.None]),
					#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					#"Replaced Value" = Table.ReplaceValue(#"Promoted Headers","NA",null,Replacer.ReplaceValue,{"county", "season", "count"}),
					#"Changed Type" = Table.TransformColumnTypes(#"Replaced Value",{  {"county", type text}, {"season", type text}, {"count", type number}   })
				in
					#"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

	measure 'Bin 1 Range' =
			VAR perc_0 =  CALCULATE ( PERCENTILE.INC (wa_bigfoot_by_county[count], 0 ), REMOVEFILTERS(wa_bigfoot_by_county[county]) )
			VAR perc_20 = CALCULATE ( PERCENTILE.INC (wa_bigfoot_by_county[count], 0.2 ), REMOVEFILTERS(wa_bigfoot_by_county[county])  )
			VAR bin1_LB = perc_0			VAR bin1_UB = IF ( perc_0 == perc_20, bin1_LB + 0.01, ROUND( perc_20, 2) )
			RETURN
			bin1_LB & "-" & bin1_UB
		lineageTag: 2766f8b7-e7a4-4aae-a82e-ce90bf6b7f79
	measure 'Bin 2 Range' =
			VAR perc_0 =  CALCULATE ( PERCENTILE.INC (wa_bigfoot_by_county[count], 0 ), REMOVEFILTERS(wa_bigfoot_by_county[county]) )
			VAR perc_20 = CALCULATE ( PERCENTILE.INC (wa_bigfoot_by_county[count], 0.2 ), REMOVEFILTERS(wa_bigfoot_by_county[county])  )
			VAR perc_40 = CALCULATE ( PERCENTILE.INC (wa_bigfoot_by_county[count], 0.4 ), REMOVEFILTERS(wa_bigfoot_by_county[county])  )
			VAR bin1_LB = perc_0			VAR bin1_UB = IF ( perc_0 == perc_20, bin1_LB + 0.01, ROUND( perc_20, 2) )
			VAR bin2_LB = bin1_UB + 0.01
			VAR bin2_UB = IF ( perc_20 == perc_40 || perc_40 <= bin2_LB, bin2_LB + 0.01, ROUND( perc_40, 2) )
			RETURN
			bin2_LB & "-" & bin2_UB
		lineageTag: eee6e750-4d1d-47a1-8dc3-3f4180aafe6d
	measure 'Bin 3 Range' =
			VAR perc_0 =  CALCULATE ( PERCENTILE.INC (wa_bigfoot_by_county[count], 0 ), REMOVEFILTERS(wa_bigfoot_by_county[county]) )
			VAR perc_20 = CALCULATE ( PERCENTILE.INC (wa_bigfoot_by_county[count], 0.2 ), REMOVEFILTERS(wa_bigfoot_by_county[county])  )
			VAR perc_40 = CALCULATE ( PERCENTILE.INC (wa_bigfoot_by_county[count], 0.4 ), REMOVEFILTERS(wa_bigfoot_by_county[county])  )
			VAR perc_60 = CALCULATE ( PERCENTILE.INC (wa_bigfoot_by_county[count], 0.6 ), REMOVEFILTERS(wa_bigfoot_by_county[county])  )
			VAR bin1_LB = perc_0			VAR bin1_UB = IF ( perc_0 == perc_20, bin1_LB + 0.01, ROUND( perc_20, 2) )
			VAR bin2_LB = bin1_UB + 0.01
			VAR bin2_UB = IF ( perc_20 == perc_40 || perc_40 <= bin2_LB, bin2_LB + 0.01, ROUND( perc_40, 2) )
			VAR bin3_LB = bin2_UB + 0.01
			VAR bin3_UB = IF ( perc_40 == perc_60 || perc_60 <= bin3_LB, bin3_LB + 0.01, ROUND( perc_60, 2) )
			RETURN
			bin3_LB & "-" & bin3_UB
		lineageTag: 1f189b16-3323-45a8-be92-4067904fb6f6
	measure 'Bin 4 Range' =
			VAR perc_0 =  CALCULATE ( PERCENTILE.INC (wa_bigfoot_by_county[count], 0 ), REMOVEFILTERS(wa_bigfoot_by_county[county]) )
			VAR perc_20 = CALCULATE ( PERCENTILE.INC (wa_bigfoot_by_county[count], 0.2 ), REMOVEFILTERS(wa_bigfoot_by_county[county])  )
			VAR perc_40 = CALCULATE ( PERCENTILE.INC (wa_bigfoot_by_county[count], 0.4 ), REMOVEFILTERS(wa_bigfoot_by_county[county])  )
			VAR perc_60 = CALCULATE ( PERCENTILE.INC (wa_bigfoot_by_county[count], 0.6 ), REMOVEFILTERS(wa_bigfoot_by_county[county])  )
			VAR perc_80 = CALCULATE ( PERCENTILE.INC (wa_bigfoot_by_county[count], 0.8 ), REMOVEFILTERS(wa_bigfoot_by_county[county])  )
			VAR bin1_LB = perc_0			VAR bin1_UB = IF ( perc_0 == perc_20, bin1_LB + 0.01, ROUND( perc_20, 2) )
			VAR bin2_LB = bin1_UB + 0.01
			VAR bin2_UB = IF ( perc_20 == perc_40 || perc_40 <= bin2_LB, bin2_LB + 0.01, ROUND( perc_40, 2) )
			VAR bin3_LB = bin2_UB + 0.01
			VAR bin3_UB = IF ( perc_40 == perc_60 || perc_60 <= bin3_LB, bin3_LB + 0.01, ROUND( perc_60, 2) )
			VAR bin4_LB = bin3_UB + 0.01
			VAR bin4_UB = IF ( perc_60 == perc_80 || perc_80 <= bin4_LB, bin4_LB + 0.01, ROUND( perc_80, 2) )
			RETURN
			bin4_LB & "-" & bin4_UB
		lineageTag: d48b17ae-e5d6-44f2-9308-853400ad68e9
	measure 'Bin 5 Range' =
			VAR perc_0 =  CALCULATE ( PERCENTILE.INC (wa_bigfoot_by_county[count], 0 ), REMOVEFILTERS(wa_bigfoot_by_county[county]) )
			VAR perc_20 = CALCULATE ( PERCENTILE.INC (wa_bigfoot_by_county[count], 0.2 ), REMOVEFILTERS(wa_bigfoot_by_county[county])  )
			VAR perc_40 = CALCULATE ( PERCENTILE.INC (wa_bigfoot_by_county[count], 0.4 ), REMOVEFILTERS(wa_bigfoot_by_county[county])  )
			VAR perc_60 = CALCULATE ( PERCENTILE.INC (wa_bigfoot_by_county[count], 0.6 ), REMOVEFILTERS(wa_bigfoot_by_county[county])  )
			VAR perc_80 = CALCULATE ( PERCENTILE.INC (wa_bigfoot_by_county[count], 0.8 ), REMOVEFILTERS(wa_bigfoot_by_county[county])  )
			VAR perc_100 = CALCULATE ( PERCENTILE.INC (wa_bigfoot_by_county[count], 1 ), REMOVEFILTERS(wa_bigfoot_by_county[county])  )
			VAR bin1_LB = perc_0			VAR bin1_UB = IF ( perc_0 == perc_20, bin1_LB + 0.01, ROUND( perc_20, 2) )
			VAR bin2_LB = bin1_UB + 0.01
			VAR bin2_UB = IF ( perc_20 == perc_40 || perc_40 <= bin2_LB, bin2_LB + 0.01, ROUND( perc_40, 2) )
			VAR bin3_LB = bin2_UB + 0.01
			VAR bin3_UB = IF ( perc_40 == perc_60 || perc_60 <= bin3_LB, bin3_LB + 0.01, ROUND( perc_60, 2) )
			VAR bin4_LB = bin3_UB + 0.01
			VAR bin4_UB = IF ( perc_60 == perc_80 || perc_80 <= bin4_LB, bin4_LB + 0.01, ROUND( perc_80, 2) )
			VAR bin5_LB = bin4_UB + 0.01
			VAR bin5_UB = IF ( perc_80 == perc_100 || perc_100 <= bin5_LB, bin5_LB + 0.01, ROUND( perc_100, 2) )
			RETURN
			bin5_LB & "-" & bin5_UB
		lineageTag: 237ba6cb-68eb-4e86-8f6d-f2e22c01e352
	measure 'Measure Value' = CALCULATE ( SUM ( wa_bigfoot_by_county[count] ))
		lineageTag: ca4ed3cf-47d7-4650-a1ac-2e175d020fdd
		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Bin Assignment Measure' = ```

		 VAR perc_0 = 
				CALCULATE ( PERCENTILE.INC (wa_bigfoot_by_county[count], 0 ), REMOVEFILTERS(wa_bigfoot_by_county[county]) )
		 VAR perc_20 = 
				CALCULATE ( PERCENTILE.INC (wa_bigfoot_by_county[count], 0.2 ), REMOVEFILTERS(wa_bigfoot_by_county[county]) )
		 VAR perc_40 = 
				CALCULATE ( PERCENTILE.INC (wa_bigfoot_by_county[count], 0.4 ), REMOVEFILTERS(wa_bigfoot_by_county[county]) )
		 VAR perc_60 = 
				CALCULATE ( PERCENTILE.INC (wa_bigfoot_by_county[count], 0.6 ), REMOVEFILTERS(wa_bigfoot_by_county[county]) )
		 VAR perc_80 = 
				CALCULATE ( PERCENTILE.INC (wa_bigfoot_by_county[count], 0.8 ), REMOVEFILTERS(wa_bigfoot_by_county[county]) )
		 VAR perc_100 = 
				CALCULATE ( PERCENTILE.INC (wa_bigfoot_by_county[count], 1 ), REMOVEFILTERS(wa_bigfoot_by_county[county]) )
			VAR bin1_LB = perc_0
			VAR bin1_UB = IF ( perc_0 == perc_20, bin1_LB + 0.01, perc_20)
			VAR bin2_LB = bin1_UB + 0.01
			VAR bin2_UB = IF ( perc_20 == perc_40 || perc_40 <= bin2_LB, bin2_LB + 0.01, perc_40 )
			VAR bin3_LB = bin2_UB + 0.01
			VAR bin3_UB = IF ( perc_40 == perc_60 || perc_60 <= bin3_LB, bin3_LB + 0.01, perc_60 )
			VAR bin4_LB = bin3_UB + 0.01
			VAR bin4_UB = IF ( perc_60 == perc_80 || perc_80 <= bin4_LB, bin4_LB + 0.01, perc_80 )
			VAR bin5_LB = bin4_UB + 0.01
			VAR bin5_UB = IF ( perc_80 == perc_100 || perc_100 <= bin5_LB, bin5_LB + 0.01, perc_100 )
			RETURN

				SWITCH (
					TRUE (),
					ISBLANK([Measure Value]), 0,
					[Measure Value] >= ROUND(bin1_LB,2) &&
					[Measure Value] <= ROUND(bin1_UB,2), 1,
					[Measure Value] >= ROUND(bin2_LB,2) &&
					[Measure Value] <= ROUND(bin2_UB,2), 2,
					[Measure Value] >= ROUND(bin3_LB,2) &&
					[Measure Value] <= ROUND(bin3_UB,2), 3,
					[Measure Value] >= ROUND(bin4_LB,2) &&
					[Measure Value] <= ROUND(bin4_UB,2), 4,
					[Measure Value] >= ROUND(bin5_LB,2) &&
					[Measure Value] <= ROUND(bin5_UB,2), 5

				)
			```
		formatString: 0
		lineageTag: 360f4181-a7d5-4090-8175-01d49ab82e0a

	measure 'Empty Bin' =

			"No Data"
		lineageTag: 0849390b-2cfa-4ede-aa42-3fa827391de7

	measure '20 percentile' = ```

				CALCULATE ( PERCENTILE.INC (wa_bigfoot_by_county[count], 0.2 ), REMOVEFILTERS(wa_bigfoot_by_county[county])  )
			```
		lineageTag: fba935ac-b57f-45c3-ab01-98e5bbddd91c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '40 percentile' = ```

				CALCULATE ( PERCENTILE.INC (wa_bigfoot_by_county[count], 0.4 ), REMOVEFILTERS(wa_bigfoot_by_county[county])  )
			```
		lineageTag: 819f0fc5-0bea-4680-a5f2-f5c49b078cb7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '60 percentile' = ```

				CALCULATE ( PERCENTILE.INC (wa_bigfoot_by_county[count], 0.6 ), REMOVEFILTERS(wa_bigfoot_by_county[county])  )
			```
		lineageTag: 53ac4f39-6f00-48fa-bbd0-d80b9fe9091d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '80 percentile' = ```

				CALCULATE ( PERCENTILE.INC (wa_bigfoot_by_county[count], 0.8 ), REMOVEFILTERS(wa_bigfoot_by_county[county])  )
			```
		lineageTag: a532884e-043b-43a0-bf02-143c404cba6f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '100 percentile' = ```

				CALCULATE ( PERCENTILE.INC (wa_bigfoot_by_county[count], 1 ), REMOVEFILTERS(wa_bigfoot_by_county[county])  )
			```
		lineageTag: b98ebbcc-bb2c-4def-9bf4-5071b8ee6e26

		annotation PBI_FormatHint = {"isGeneralNumber":true}

